


export const Student_Data = [
    {
        "id": 1,
        "first_name": "Paul",
        "last_name": "Casey",
        "email": "paul.casey.1@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 3,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 27,
        "career_aspiration": "Lawyer",
        "math_score": 73,
        "history_score": 81,
        "physics_score": 93,
        "chemistry_score": 97,
        "biology_score": 63,
        "english_score": 80,
        "geography_score": 87
      },
      {
        "id": 2,
        "first_name": "Danielle",
        "last_name": "Sandoval",
        "email": "danielle.sandoval.2@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 2,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 47,
        "career_aspiration": "Doctor",
        "math_score": 90,
        "history_score": 86,
        "physics_score": 96,
        "chemistry_score": 100,
        "biology_score": 90,
        "english_score": 88,
        "geography_score": 90
      },
      {
        "id": 3,
        "first_name": "Tina",
        "last_name": "Andrews",
        "email": "tina.andrews.3@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 9,
        "extracurricular_activities": true,
        "weekly_self_study_hours": 13,
        "career_aspiration": "Government Officer",
        "math_score": 81,
        "history_score": 97,
        "physics_score": 95,
        "chemistry_score": 96,
        "biology_score": 65,
        "english_score": 77,
        "geography_score": 94
      },
      {
        "id": 4,
        "first_name": "Tara",
        "last_name": "Clark",
        "email": "tara.clark.4@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 5,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 3,
        "career_aspiration": "Artist",
        "math_score": 71,
        "history_score": 74,
        "physics_score": 88,
        "chemistry_score": 80,
        "biology_score": 89,
        "english_score": 63,
        "geography_score": 86
      },
      {
        "id": 5,
        "first_name": "Anthony",
        "last_name": "Campos",
        "email": "anthony.campos.5@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 5,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 10,
        "career_aspiration": "Unknown",
        "math_score": 84,
        "history_score": 77,
        "physics_score": 65,
        "chemistry_score": 65,
        "biology_score": 80,
        "english_score": 74,
        "geography_score": 76
      },
      {
        "id": 6,
        "first_name": "Kelly",
        "last_name": "Wade",
        "email": "kelly.wade.6@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 2,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 26,
        "career_aspiration": "Unknown",
        "math_score": 93,
        "history_score": 100,
        "physics_score": 67,
        "chemistry_score": 78,
        "biology_score": 72,
        "english_score": 80,
        "geography_score": 84
      },
      {
        "id": 7,
        "first_name": "Anthony",
        "last_name": "Smith",
        "email": "anthony.smith.7@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 3,
        "extracurricular_activities": true,
        "weekly_self_study_hours": 23,
        "career_aspiration": "Software Engineer",
        "math_score": 99,
        "history_score": 96,
        "physics_score": 97,
        "chemistry_score": 73,
        "biology_score": 88,
        "english_score": 76,
        "geography_score": 64
      },
      {
        "id": 8,
        "first_name": "George",
        "last_name": "Short",
        "email": "george.short.8@gslingacademy.com",
        "gender": "male",
        "part_time_job": true,
        "absence_days": 2,
        "extracurricular_activities": true,
        "weekly_self_study_hours": 34,
        "career_aspiration": "Software Engineer",
        "math_score": 95,
        "history_score": 95,
        "physics_score": 82,
        "chemistry_score": 63,
        "biology_score": 84,
        "english_score": 70,
        "geography_score": 85
      },
      {
        "id": 9,
        "first_name": "Stanley",
        "last_name": "Gutierrez",
        "email": "stanley.gutierrez.9@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 6,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 25,
        "career_aspiration": "Unknown",
        "math_score": 94,
        "history_score": 68,
        "physics_score": 94,
        "chemistry_score": 85,
        "biology_score": 81,
        "english_score": 74,
        "geography_score": 72
      },
      {
        "id": 10,
        "first_name": "Audrey",
        "last_name": "Simpson",
        "email": "audrey.simpson.10@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 3,
        "extracurricular_activities": true,
        "weekly_self_study_hours": 18,
        "career_aspiration": "Teacher",
        "math_score": 98,
        "history_score": 69,
        "physics_score": 88,
        "chemistry_score": 71,
        "biology_score": 67,
        "english_score": 71,
        "geography_score": 73
      },
      {
        "id": 11,
        "first_name": "Gabrielle",
        "last_name": "White",
        "email": "gabrielle.white.11@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 2,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 7,
        "career_aspiration": "Teacher",
        "math_score": 65,
        "history_score": 60,
        "physics_score": 97,
        "chemistry_score": 94,
        "biology_score": 71,
        "english_score": 81,
        "geography_score": 66
      },
      {
        "id": 12,
        "first_name": "Clinton",
        "last_name": "Randolph",
        "email": "clinton.randolph.12@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 1,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 7,
        "career_aspiration": "Unknown",
        "math_score": 80,
        "history_score": 61,
        "physics_score": 100,
        "chemistry_score": 65,
        "biology_score": 87,
        "english_score": 64,
        "geography_score": 61
      },
      {
        "id": 13,
        "first_name": "Patricia",
        "last_name": "Gomez",
        "email": "patricia.gomez.13@gslingacademy.com",
        "gender": "female",
        "part_time_job": true,
        "absence_days": 7,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 4,
        "career_aspiration": "Business Owner",
        "math_score": 94,
        "history_score": 59,
        "physics_score": 69,
        "chemistry_score": 67,
        "biology_score": 89,
        "english_score": 65,
        "geography_score": 73
      },
      {
        "id": 14,
        "first_name": "Pamela",
        "last_name": "Jackson",
        "email": "pamela.jackson.14@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 10,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 2,
        "career_aspiration": "Business Owner",
        "math_score": 66,
        "history_score": 94,
        "physics_score": 86,
        "chemistry_score": 100,
        "biology_score": 57,
        "english_score": 90,
        "geography_score": 63
      },
      {
        "id": 15,
        "first_name": "Laura",
        "last_name": "Jackson",
        "email": "laura.jackson.15@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 3,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 39,
        "career_aspiration": "Doctor",
        "math_score": 96,
        "history_score": 90,
        "physics_score": 86,
        "chemistry_score": 92,
        "biology_score": 92,
        "english_score": 95,
        "geography_score": 87
      },
      {
        "id": 16,
        "first_name": "Roger",
        "last_name": "Wiley",
        "email": "roger.wiley.16@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 6,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 0,
        "career_aspiration": "Business Owner",
        "math_score": 94,
        "history_score": 50,
        "physics_score": 78,
        "chemistry_score": 64,
        "biology_score": 79,
        "english_score": 74,
        "geography_score": 84
      },
      {
        "id": 17,
        "first_name": "Vicki",
        "last_name": "Thompson",
        "email": "vicki.thompson.17@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 3,
        "extracurricular_activities": true,
        "weekly_self_study_hours": 30,
        "career_aspiration": "Scientist",
        "math_score": 92,
        "history_score": 64,
        "physics_score": 93,
        "chemistry_score": 91,
        "biology_score": 80,
        "english_score": 89,
        "geography_score": 72
      },
      {
        "id": 18,
        "first_name": "Maxwell",
        "last_name": "Davidson",
        "email": "maxwell.davidson.18@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 2,
        "extracurricular_activities": true,
        "weekly_self_study_hours": 28,
        "career_aspiration": "Software Engineer",
        "math_score": 86,
        "history_score": 83,
        "physics_score": 85,
        "chemistry_score": 79,
        "biology_score": 93,
        "english_score": 76,
        "geography_score": 77
      },
      {
        "id": 19,
        "first_name": "Jonathan",
        "last_name": "Werner",
        "email": "jonathan.werner.19@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 1,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 37,
        "career_aspiration": "Doctor",
        "math_score": 92,
        "history_score": 87,
        "physics_score": 92,
        "chemistry_score": 99,
        "biology_score": 97,
        "english_score": 87,
        "geography_score": 86
      },
      {
        "id": 20,
        "first_name": "Angela",
        "last_name": "Rios",
        "email": "angela.rios.20@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 2,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 27,
        "career_aspiration": "Software Engineer",
        "math_score": 99,
        "history_score": 65,
        "physics_score": 98,
        "chemistry_score": 75,
        "biology_score": 66,
        "english_score": 72,
        "geography_score": 100
      },
      {
        "id": 21,
        "first_name": "Tim",
        "last_name": "Nichols",
        "email": "tim.nichols.21@gslingacademy.com",
        "gender": "male",
        "part_time_job": true,
        "absence_days": 3,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 15,
        "career_aspiration": "Software Engineer",
        "math_score": 100,
        "history_score": 90,
        "physics_score": 72,
        "chemistry_score": 98,
        "biology_score": 73,
        "english_score": 97,
        "geography_score": 72
      },
      {
        "id": 22,
        "first_name": "Kyle",
        "last_name": "Willis",
        "email": "kyle.willis.22@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 8,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 4,
        "career_aspiration": "Business Owner",
        "math_score": 57,
        "history_score": 55,
        "physics_score": 78,
        "chemistry_score": 94,
        "biology_score": 83,
        "english_score": 88,
        "geography_score": 88
      },
      {
        "id": 23,
        "first_name": "Shannon",
        "last_name": "Simpson",
        "email": "shannon.simpson.23@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 9,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 2,
        "career_aspiration": "Business Owner",
        "math_score": 89,
        "history_score": 72,
        "physics_score": 68,
        "chemistry_score": 72,
        "biology_score": 71,
        "english_score": 54,
        "geography_score": 90
      },
      {
        "id": 24,
        "first_name": "Sean",
        "last_name": "Griffin",
        "email": "sean.griffin.24@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 9,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 1,
        "career_aspiration": "Business Owner",
        "math_score": 50,
        "history_score": 76,
        "physics_score": 81,
        "chemistry_score": 55,
        "biology_score": 56,
        "english_score": 80,
        "geography_score": 79
      },
      {
        "id": 25,
        "first_name": "Cassandra",
        "last_name": "West",
        "email": "cassandra.west.25@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 4,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 35,
        "career_aspiration": "Software Engineer",
        "math_score": 87,
        "history_score": 91,
        "physics_score": 90,
        "chemistry_score": 88,
        "biology_score": 95,
        "english_score": 88,
        "geography_score": 93
      },
      {
        "id": 26,
        "first_name": "Patricia",
        "last_name": "Chavez",
        "email": "patricia.chavez.26@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 5,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 22,
        "career_aspiration": "Doctor",
        "math_score": 92,
        "history_score": 86,
        "physics_score": 87,
        "chemistry_score": 81,
        "biology_score": 93,
        "english_score": 90,
        "geography_score": 99
      },
      {
        "id": 27,
        "first_name": "Jason",
        "last_name": "Williams",
        "email": "jason.williams.27@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 3,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 34,
        "career_aspiration": "Banker",
        "math_score": 100,
        "history_score": 77,
        "physics_score": 80,
        "chemistry_score": 94,
        "biology_score": 63,
        "english_score": 90,
        "geography_score": 90
      },
      {
        "id": 28,
        "first_name": "Peter",
        "last_name": "Gibbs",
        "email": "peter.gibbs.28@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 0,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 23,
        "career_aspiration": "Writer",
        "math_score": 64,
        "history_score": 75,
        "physics_score": 93,
        "chemistry_score": 79,
        "biology_score": 81,
        "english_score": 96,
        "geography_score": 85
      },
      {
        "id": 29,
        "first_name": "Jeffrey",
        "last_name": "Blanchard",
        "email": "jeffrey.blanchard.29@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 1,
        "extracurricular_activities": true,
        "weekly_self_study_hours": 17,
        "career_aspiration": "Accountant",
        "math_score": 79,
        "history_score": 65,
        "physics_score": 99,
        "chemistry_score": 71,
        "biology_score": 76,
        "english_score": 77,
        "geography_score": 83
      },
      {
        "id": 30,
        "first_name": "Carol",
        "last_name": "Hill",
        "email": "carol.hill.30@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 3,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 19,
        "career_aspiration": "Accountant",
        "math_score": 82,
        "history_score": 100,
        "physics_score": 61,
        "chemistry_score": 97,
        "biology_score": 30,
        "english_score": 74,
        "geography_score": 73
      },
      {
        "id": 31,
        "first_name": "Angie",
        "last_name": "Miller",
        "email": "angie.miller.31@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 0,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 14,
        "career_aspiration": "Software Engineer",
        "math_score": 88,
        "history_score": 69,
        "physics_score": 87,
        "chemistry_score": 100,
        "biology_score": 88,
        "english_score": 85,
        "geography_score": 72
      },
      {
        "id": 32,
        "first_name": "Cynthia",
        "last_name": "Knapp",
        "email": "cynthia.knapp.32@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 4,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 30,
        "career_aspiration": "Designer",
        "math_score": 70,
        "history_score": 68,
        "physics_score": 92,
        "chemistry_score": 74,
        "biology_score": 82,
        "english_score": 85,
        "geography_score": 72
      },
      {
        "id": 33,
        "first_name": "Timothy",
        "last_name": "Bryant",
        "email": "timothy.bryant.33@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 4,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 30,
        "career_aspiration": "Accountant",
        "math_score": 77,
        "history_score": 96,
        "physics_score": 98,
        "chemistry_score": 89,
        "biology_score": 85,
        "english_score": 62,
        "geography_score": 62
      },
      {
        "id": 34,
        "first_name": "Phyllis",
        "last_name": "Diaz",
        "email": "phyllis.diaz.34@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 1,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 24,
        "career_aspiration": "Banker",
        "math_score": 99,
        "history_score": 84,
        "physics_score": 84,
        "chemistry_score": 78,
        "biology_score": 78,
        "english_score": 77,
        "geography_score": 68
      },
      {
        "id": 35,
        "first_name": "Lisa",
        "last_name": "Burns",
        "email": "lisa.burns.35@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 3,
        "extracurricular_activities": true,
        "weekly_self_study_hours": 31,
        "career_aspiration": "Unknown",
        "math_score": 90,
        "history_score": 93,
        "physics_score": 91,
        "chemistry_score": 80,
        "biology_score": 86,
        "english_score": 69,
        "geography_score": 62
      },
      {
        "id": 36,
        "first_name": "Kelly",
        "last_name": "Farley",
        "email": "kelly.farley.36@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 1,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 21,
        "career_aspiration": "Unknown",
        "math_score": 65,
        "history_score": 70,
        "physics_score": 78,
        "chemistry_score": 98,
        "biology_score": 80,
        "english_score": 66,
        "geography_score": 65
      },
      {
        "id": 37,
        "first_name": "Ryan",
        "last_name": "Lee",
        "email": "ryan.lee.37@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 2,
        "extracurricular_activities": true,
        "weekly_self_study_hours": 19,
        "career_aspiration": "Construction Engineer",
        "math_score": 99,
        "history_score": 94,
        "physics_score": 87,
        "chemistry_score": 71,
        "biology_score": 89,
        "english_score": 91,
        "geography_score": 96
      },
      {
        "id": 38,
        "first_name": "Michael",
        "last_name": "Gilmore",
        "email": "michael.gilmore.38@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 1,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 29,
        "career_aspiration": "Construction Engineer",
        "math_score": 92,
        "history_score": 100,
        "physics_score": 85,
        "chemistry_score": 89,
        "biology_score": 81,
        "english_score": 91,
        "geography_score": 88
      },
      {
        "id": 39,
        "first_name": "Miguel",
        "last_name": "Martinez",
        "email": "miguel.martinez.39@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 4,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 21,
        "career_aspiration": "Banker",
        "math_score": 77,
        "history_score": 64,
        "physics_score": 64,
        "chemistry_score": 88,
        "biology_score": 94,
        "english_score": 82,
        "geography_score": 78
      },
      {
        "id": 40,
        "first_name": "Christopher",
        "last_name": "Taylor",
        "email": "christopher.taylor.40@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 4,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 18,
        "career_aspiration": "Accountant",
        "math_score": 92,
        "history_score": 60,
        "physics_score": 66,
        "chemistry_score": 87,
        "biology_score": 60,
        "english_score": 83,
        "geography_score": 95
      },
      {
        "id": 41,
        "first_name": "Emily",
        "last_name": "Holloway",
        "email": "emily.holloway.41@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 4,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 31,
        "career_aspiration": "Software Engineer",
        "math_score": 85,
        "history_score": 97,
        "physics_score": 64,
        "chemistry_score": 90,
        "biology_score": 79,
        "english_score": 81,
        "geography_score": 81
      },
      {
        "id": 42,
        "first_name": "Jesus",
        "last_name": "Rasmussen",
        "email": "jesus.rasmussen.42@gslingacademy.com",
        "gender": "male",
        "part_time_job": true,
        "absence_days": 7,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 4,
        "career_aspiration": "Business Owner",
        "math_score": 65,
        "history_score": 55,
        "physics_score": 66,
        "chemistry_score": 50,
        "biology_score": 88,
        "english_score": 56,
        "geography_score": 86
      },
      {
        "id": 43,
        "first_name": "Lauren",
        "last_name": "Farmer",
        "email": "lauren.farmer.43@gslingacademy.com",
        "gender": "female",
        "part_time_job": true,
        "absence_days": 6,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 3,
        "career_aspiration": "Business Owner",
        "math_score": 93,
        "history_score": 94,
        "physics_score": 92,
        "chemistry_score": 77,
        "biology_score": 87,
        "english_score": 98,
        "geography_score": 63
      },
      {
        "id": 44,
        "first_name": "Pamela",
        "last_name": "Cole",
        "email": "pamela.cole.44@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 4,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 3,
        "career_aspiration": "Game Developer",
        "math_score": 97,
        "history_score": 99,
        "physics_score": 85,
        "chemistry_score": 96,
        "biology_score": 91,
        "english_score": 68,
        "geography_score": 66
      },
      {
        "id": 45,
        "first_name": "David",
        "last_name": "Gillespie",
        "email": "david.gillespie.45@gslingacademy.com",
        "gender": "male",
        "part_time_job": true,
        "absence_days": 4,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 3,
        "career_aspiration": "Business Owner",
        "math_score": 54,
        "history_score": 99,
        "physics_score": 79,
        "chemistry_score": 57,
        "biology_score": 53,
        "english_score": 95,
        "geography_score": 83
      },
      {
        "id": 46,
        "first_name": "Kenneth",
        "last_name": "Davis",
        "email": "kenneth.davis.46@gslingacademy.com",
        "gender": "male",
        "part_time_job": true,
        "absence_days": 5,
        "extracurricular_activities": true,
        "weekly_self_study_hours": 5,
        "career_aspiration": "Business Owner",
        "math_score": 88,
        "history_score": 53,
        "physics_score": 50,
        "chemistry_score": 58,
        "biology_score": 84,
        "english_score": 53,
        "geography_score": 96
      },
      {
        "id": 47,
        "first_name": "Elizabeth",
        "last_name": "Martin",
        "email": "elizabeth.martin.47@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 5,
        "extracurricular_activities": true,
        "weekly_self_study_hours": 27,
        "career_aspiration": "Lawyer",
        "math_score": 71,
        "history_score": 85,
        "physics_score": 93,
        "chemistry_score": 68,
        "biology_score": 100,
        "english_score": 91,
        "geography_score": 87
      },
      {
        "id": 48,
        "first_name": "Billy",
        "last_name": "Soto",
        "email": "billy.soto.48@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 0,
        "extracurricular_activities": true,
        "weekly_self_study_hours": 28,
        "career_aspiration": "Stock Investor",
        "math_score": 81,
        "history_score": 98,
        "physics_score": 74,
        "chemistry_score": 70,
        "biology_score": 97,
        "english_score": 65,
        "geography_score": 65
      },
      {
        "id": 49,
        "first_name": "Kimberly",
        "last_name": "Kelly",
        "email": "kimberly.kelly.49@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 4,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 32,
        "career_aspiration": "Unknown",
        "math_score": 80,
        "history_score": 78,
        "physics_score": 86,
        "chemistry_score": 80,
        "biology_score": 64,
        "english_score": 68,
        "geography_score": 100
      },
      {
        "id": 50,
        "first_name": "Sonia",
        "last_name": "Noble",
        "email": "sonia.noble.50@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 0,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 14,
        "career_aspiration": "Accountant",
        "math_score": 100,
        "history_score": 89,
        "physics_score": 90,
        "chemistry_score": 93,
        "biology_score": 30,
        "english_score": 83,
        "geography_score": 74
      },
      {
        "id": 51,
        "first_name": "Christopher",
        "last_name": "Stewart",
        "email": "christopher.stewart.51@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 6,
        "extracurricular_activities": true,
        "weekly_self_study_hours": 16,
        "career_aspiration": "Stock Investor",
        "math_score": 76,
        "history_score": 72,
        "physics_score": 96,
        "chemistry_score": 65,
        "biology_score": 89,
        "english_score": 87,
        "geography_score": 94
      },
      {
        "id": 52,
        "first_name": "Sandra",
        "last_name": "Thornton",
        "email": "sandra.thornton.52@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 2,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 24,
        "career_aspiration": "Lawyer",
        "math_score": 99,
        "history_score": 81,
        "physics_score": 73,
        "chemistry_score": 70,
        "biology_score": 85,
        "english_score": 86,
        "geography_score": 61
      },
      {
        "id": 53,
        "first_name": "Luke",
        "last_name": "Shannon",
        "email": "luke.shannon.53@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 9,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 0,
        "career_aspiration": "Business Owner",
        "math_score": 64,
        "history_score": 70,
        "physics_score": 61,
        "chemistry_score": 81,
        "biology_score": 82,
        "english_score": 51,
        "geography_score": 70
      },
      {
        "id": 54,
        "first_name": "Lindsay",
        "last_name": "Pruitt",
        "email": "lindsay.pruitt.54@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 3,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 32,
        "career_aspiration": "Banker",
        "math_score": 90,
        "history_score": 96,
        "physics_score": 86,
        "chemistry_score": 61,
        "biology_score": 89,
        "english_score": 98,
        "geography_score": 68
      },
      {
        "id": 55,
        "first_name": "Jamie",
        "last_name": "Taylor",
        "email": "jamie.taylor.55@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 2,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 3,
        "career_aspiration": "Game Developer",
        "math_score": 85,
        "history_score": 100,
        "physics_score": 92,
        "chemistry_score": 68,
        "biology_score": 60,
        "english_score": 77,
        "geography_score": 83
      },
      {
        "id": 56,
        "first_name": "Jennifer",
        "last_name": "Murphy",
        "email": "jennifer.murphy.56@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 6,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 31,
        "career_aspiration": "Software Engineer",
        "math_score": 91,
        "history_score": 60,
        "physics_score": 84,
        "chemistry_score": 88,
        "biology_score": 76,
        "english_score": 71,
        "geography_score": 99
      },
      {
        "id": 57,
        "first_name": "Melissa",
        "last_name": "Lee",
        "email": "melissa.lee.57@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 3,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 21,
        "career_aspiration": "Unknown",
        "math_score": 95,
        "history_score": 72,
        "physics_score": 79,
        "chemistry_score": 86,
        "biology_score": 87,
        "english_score": 81,
        "geography_score": 62
      },
      {
        "id": 58,
        "first_name": "David",
        "last_name": "Vaughn",
        "email": "david.vaughn.58@gslingacademy.com",
        "gender": "male",
        "part_time_job": true,
        "absence_days": 2,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 18,
        "career_aspiration": "Banker",
        "math_score": 94,
        "history_score": 78,
        "physics_score": 73,
        "chemistry_score": 97,
        "biology_score": 67,
        "english_score": 78,
        "geography_score": 99
      },
      {
        "id": 59,
        "first_name": "Jacob",
        "last_name": "Hanson",
        "email": "jacob.hanson.59@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 7,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 26,
        "career_aspiration": "Software Engineer",
        "math_score": 94,
        "history_score": 89,
        "physics_score": 64,
        "chemistry_score": 96,
        "biology_score": 91,
        "english_score": 95,
        "geography_score": 77
      },
      {
        "id": 60,
        "first_name": "Casey",
        "last_name": "May",
        "email": "casey.may.60@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 4,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 23,
        "career_aspiration": "Software Engineer",
        "math_score": 89,
        "history_score": 99,
        "physics_score": 90,
        "chemistry_score": 79,
        "biology_score": 85,
        "english_score": 96,
        "geography_score": 98
      },
      {
        "id": 61,
        "first_name": "Michelle",
        "last_name": "Roman",
        "email": "michelle.roman.61@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 2,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 1,
        "career_aspiration": "Game Developer",
        "math_score": 91,
        "history_score": 81,
        "physics_score": 88,
        "chemistry_score": 71,
        "biology_score": 78,
        "english_score": 83,
        "geography_score": 76
      },
      {
        "id": 62,
        "first_name": "Brittany",
        "last_name": "Koch",
        "email": "brittany.koch.62@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 5,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 33,
        "career_aspiration": "Lawyer",
        "math_score": 83,
        "history_score": 86,
        "physics_score": 61,
        "chemistry_score": 99,
        "biology_score": 99,
        "english_score": 88,
        "geography_score": 73
      },
      {
        "id": 63,
        "first_name": "Brian",
        "last_name": "Lewis",
        "email": "brian.lewis.63@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 7,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 2,
        "career_aspiration": "Business Owner",
        "math_score": 98,
        "history_score": 65,
        "physics_score": 53,
        "chemistry_score": 64,
        "biology_score": 52,
        "english_score": 96,
        "geography_score": 62
      },
      {
        "id": 64,
        "first_name": "Veronica",
        "last_name": "Cameron",
        "email": "veronica.cameron.64@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 1,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 34,
        "career_aspiration": "Banker",
        "math_score": 83,
        "history_score": 97,
        "physics_score": 65,
        "chemistry_score": 88,
        "biology_score": 67,
        "english_score": 95,
        "geography_score": 69
      },
      {
        "id": 65,
        "first_name": "Eric",
        "last_name": "Reyes",
        "email": "eric.reyes.65@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 2,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 18,
        "career_aspiration": "Construction Engineer",
        "math_score": 91,
        "history_score": 73,
        "physics_score": 99,
        "chemistry_score": 70,
        "biology_score": 63,
        "english_score": 80,
        "geography_score": 78
      },
      {
        "id": 66,
        "first_name": "Kristy",
        "last_name": "Weber",
        "email": "kristy.weber.66@gslingacademy.com",
        "gender": "female",
        "part_time_job": true,
        "absence_days": 6,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 2,
        "career_aspiration": "Business Owner",
        "math_score": 90,
        "history_score": 54,
        "physics_score": 77,
        "chemistry_score": 74,
        "biology_score": 76,
        "english_score": 96,
        "geography_score": 88
      },
      {
        "id": 67,
        "first_name": "Anthony",
        "last_name": "Smith",
        "email": "anthony.smith.67@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 3,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 27,
        "career_aspiration": "Software Engineer",
        "math_score": 92,
        "history_score": 86,
        "physics_score": 66,
        "chemistry_score": 69,
        "biology_score": 100,
        "english_score": 71,
        "geography_score": 80
      },
      {
        "id": 68,
        "first_name": "Steven",
        "last_name": "Stephens",
        "email": "steven.stephens.68@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 2,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 8,
        "career_aspiration": "Real Estate Developer",
        "math_score": 64,
        "history_score": 64,
        "physics_score": 73,
        "chemistry_score": 76,
        "biology_score": 72,
        "english_score": 97,
        "geography_score": 91
      },
      {
        "id": 69,
        "first_name": "Henry",
        "last_name": "Davis",
        "email": "henry.davis.69@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 4,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 14,
        "career_aspiration": "Software Engineer",
        "math_score": 90,
        "history_score": 70,
        "physics_score": 85,
        "chemistry_score": 60,
        "biology_score": 81,
        "english_score": 71,
        "geography_score": 88
      },
      {
        "id": 70,
        "first_name": "Raymond",
        "last_name": "Shea",
        "email": "raymond.shea.70@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 10,
        "extracurricular_activities": true,
        "weekly_self_study_hours": 22,
        "career_aspiration": "Banker",
        "math_score": 99,
        "history_score": 81,
        "physics_score": 96,
        "chemistry_score": 69,
        "biology_score": 91,
        "english_score": 87,
        "geography_score": 83
      },
      {
        "id": 71,
        "first_name": "Jill",
        "last_name": "Perez",
        "email": "jill.perez.71@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 1,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 15,
        "career_aspiration": "Designer",
        "math_score": 89,
        "history_score": 66,
        "physics_score": 93,
        "chemistry_score": 81,
        "biology_score": 86,
        "english_score": 88,
        "geography_score": 70
      },
      {
        "id": 72,
        "first_name": "Kimberly",
        "last_name": "Bonilla",
        "email": "kimberly.bonilla.72@gslingacademy.com",
        "gender": "female",
        "part_time_job": true,
        "absence_days": 3,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 22,
        "career_aspiration": "Writer",
        "math_score": 62,
        "history_score": 87,
        "physics_score": 93,
        "chemistry_score": 83,
        "biology_score": 93,
        "english_score": 97,
        "geography_score": 73
      },
      {
        "id": 73,
        "first_name": "Louis",
        "last_name": "Edwards",
        "email": "louis.edwards.73@gslingacademy.com",
        "gender": "male",
        "part_time_job": true,
        "absence_days": 10,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 1,
        "career_aspiration": "Business Owner",
        "math_score": 61,
        "history_score": 70,
        "physics_score": 69,
        "chemistry_score": 64,
        "biology_score": 59,
        "english_score": 78,
        "geography_score": 80
      },
      {
        "id": 74,
        "first_name": "Michael",
        "last_name": "Hodge",
        "email": "michael.hodge.74@gslingacademy.com",
        "gender": "male",
        "part_time_job": true,
        "absence_days": 8,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 3,
        "career_aspiration": "Business Owner",
        "math_score": 51,
        "history_score": 54,
        "physics_score": 66,
        "chemistry_score": 87,
        "biology_score": 99,
        "english_score": 58,
        "geography_score": 68
      },
      {
        "id": 75,
        "first_name": "Anna",
        "last_name": "Li",
        "email": "anna.li.75@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 2,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 20,
        "career_aspiration": "Software Engineer",
        "math_score": 85,
        "history_score": 100,
        "physics_score": 64,
        "chemistry_score": 68,
        "biology_score": 73,
        "english_score": 81,
        "geography_score": 87
      },
      {
        "id": 76,
        "first_name": "Andrea",
        "last_name": "Case",
        "email": "andrea.case.76@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 7,
        "extracurricular_activities": true,
        "weekly_self_study_hours": 27,
        "career_aspiration": "Software Engineer",
        "math_score": 99,
        "history_score": 90,
        "physics_score": 96,
        "chemistry_score": 92,
        "biology_score": 100,
        "english_score": 98,
        "geography_score": 77
      },
      {
        "id": 77,
        "first_name": "Jennifer",
        "last_name": "Garcia",
        "email": "jennifer.garcia.77@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 3,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 24,
        "career_aspiration": "Software Engineer",
        "math_score": 87,
        "history_score": 63,
        "physics_score": 60,
        "chemistry_score": 90,
        "biology_score": 89,
        "english_score": 99,
        "geography_score": 80
      },
      {
        "id": 78,
        "first_name": "Rhonda",
        "last_name": "Davenport",
        "email": "rhonda.davenport.78@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 1,
        "extracurricular_activities": true,
        "weekly_self_study_hours": 5,
        "career_aspiration": "Unknown",
        "math_score": 75,
        "history_score": 91,
        "physics_score": 80,
        "chemistry_score": 93,
        "biology_score": 74,
        "english_score": 93,
        "geography_score": 65
      },
      {
        "id": 79,
        "first_name": "Chelsea",
        "last_name": "Craig",
        "email": "chelsea.craig.79@gslingacademy.com",
        "gender": "female",
        "part_time_job": false,
        "absence_days": 7,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 34,
        "career_aspiration": "Unknown",
        "math_score": 88,
        "history_score": 94,
        "physics_score": 80,
        "chemistry_score": 63,
        "biology_score": 68,
        "english_score": 77,
        "geography_score": 64
      },
      {
        "id": 80,
        "first_name": "Shawn",
        "last_name": "Chase",
        "email": "shawn.chase.80@gslingacademy.com",
        "gender": "male",
        "part_time_job": false,
        "absence_days": 3,
        "extracurricular_activities": false,
        "weekly_self_study_hours": 16,
        "career_aspiration": "Software Engineer",
        "math_score": 87,
        "history_score": 79,
        "physics_score": 89,
        "chemistry_score": 68,
        "biology_score": 93,
        "english_score": 75,
        "geography_score": 92
      }
]